PRIMARY = "#E56353" #Naranja Quemado
SECONDARY = "#86C8BC" #Verde

HOVER_PRIMARY = "#D35D4F"
HOVER_SECONDARY = "#77ADA3"

BG_DARK = "#607D8B" #Gris Azulado
BG_LIGHT = "#EEEEEE" #Gris claro

BG_LOGIN = "#F1F1F1"
NAV = "#F6F6F6"

TEXT = "#34495E" #Gris oscuro
TEXT_LIGHT = "#FAFAFA"
TEXT_BUTTON = "#FBFCFC"
HOVER_NAV = "#D6DBDF"